# Generated by Django 4.0.4 on 2022-04-28 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_area', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('vote_count', models.IntegerField(default=0)),
                ('quize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sambho.quize')),
            ],
        ),
    ]
