# Generated by Django 4.0.4 on 2022-05-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sambho', '0002_basemodel_color_people_peopleaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Colors',
        ),
    ]
