# Generated by Django 4.0.4 on 2022-05-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sambho', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_runner', models.CharField(max_length=600)),
                ('medal_choice', models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Solver', 'Solver'), ('Bronze', 'Bronze')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
