# Generated by Django 4.0.4 on 2022-05-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sambho', '0006_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbosExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="person's first name")),
                ('first_name_again', models.CharField(max_length=30)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sambho.fruit', verbose_name='the related name')),
                ('runner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sambho.runner', verbose_name='runner ups')),
            ],
        ),
    ]
