# Generated by Django 4.0.4 on 2022-05-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sambho', '0007_verbosexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyToManyField_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbosexamples', models.ManyToManyField(to='sambho.verbosexample')),
            ],
        ),
    ]
