# Generated by Django 4.0.4 on 2022-05-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sambho', '0009_group_person_many_membership_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='ox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horn_length', models.IntegerField()),
            ],
        ),
    ]
